trigger:
- master

pool:
# A windows agent is required to execute the plugin tasks
 vmImage: windows-2022

steps:
# Install Platform step will install the CLI which is self-contained in this task.
# If this task is not used, the CLI will be downloaded from an external nuget feed
- task: UiPathInstallPlatform@2

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'staging.uipath.com'
    testProjectPath: '$(Build.ArtifactStagingDirectory)\OutsystemsDemo'
    folderName: 'Thomas Stocker Modern Folder'
    testReportDestination: '$(Build.ArtifactStagingDirectory)\output'
